name: pytorch
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.2.0=py36_0
  - astor=0.6.2=py36_0
  - ca-certificates=2018.03.07=0
  - cffi=1.11.5=py36h9745a5d_0
  - fontconfig=2.12.4=h88586e7_1
  - freetype=2.8=hab7d2ae_1
  - gast=0.2.0=py36_0
  - glib=2.53.6=h5d9569c_2
  - grpcio=1.11.0=py36hf484d3e_0
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2018.0.0=8
  - jbig=2.1=hdba287a_0
  - jpeg=9b=h024ee3a_2
  - lazy-object-proxy=1.3.1=py36h10fcdad_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.5.2=h6f1eeef_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=h28f6b97_0
  - libxml2=2.9.4=0
  - markdown=2.6.11=py36_0
  - matplotlib=2.2.2=py36h0e671d2_0
  - mccabe=0.6.1=py36h5ad9710_1
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - ncurses=6.0=h9df7e31_2
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.14.2=py36hdbf6ddf_1
  - openssl=1.0.2o=h20670df_0
  - pandas=0.22.0=py36hf484d3e_0
  - pep8=1.7.1=py36_0
  - pillow=5.1.0=py36h3deb7b8_0
  - protobuf=3.5.2=py36hf484d3e_0
  - pycparser=2.18=py36hf9f622e_1
  - python=3.6.5=hc3d631a_0
  - python-dateutil=2.7.2=py36_0
  - pytz=2018.4=py36_0
  - pyyaml=3.12=py36hafb9ca4_1
  - qt=5.6.2=h974d657_12
  - readline=7.0=ha6073c6_4
  - scikit-learn=0.19.1=py36h7aa7ec6_0
  - scipy=1.0.1=py36hfc37229_0
  - six=1.11.0=py36h372c433_1
  - sqlite=3.23.1=he433501_0
  - tensorboard=1.7.0=py36hf484d3e_1
  - tensorflow=1.7.0=0
  - tensorflow-base=1.7.0=py36hdbcaa40_2
  - tk=8.6.7=hc745277_3
  - werkzeug=0.14.1=py36_0
  - wrapt=1.10.11=py36h28b7045_0
  - xz=5.2.3=h55aa19d_2
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=ha838bed_2
  - asn1crypto=0.24.0=py36_0
  - astroid=1.6.3=py36_0
  - audioread=2.1.4=py36_2
  - bleach=1.5.0=py36_0
  - bzip2=1.0.6=1
  - certifi=2018.4.16=py36_0
  - chardet=3.0.4=py36_0
  - codecov=2.0.9=py36_0
  - coverage=4.5.1=py36_0
  - cryptography=2.2.1=py36_0
  - cycler=0.10.0=py36_0
  - dbus=1.10.22=0
  - decorator=4.3.0=py_0
  - expat=2.2.5=0
  - ffmpeg=2.8.6=5
  - hdf5=1.8.17=2
  - html5lib=0.9999999=py36_0
  - idna=2.6=py36_1
  - isort=4.3.4=py36_0
  - jasper=1.900.1=4
  - joblib=0.11=py36_0
  - kiwisolver=1.0.1=py36_1
  - libiconv=1.15=0
  - librosa=0.6.0=py36_0
  - libxcb=1.13=0
  - llvmlite=0.21.0=py36_0
  - numba=0.36.1=py36hdc42b47_0
  - olefile=0.45.1=py36_0
  - pcre=8.41=1
  - pip=9.0.3=py36_0
  - pylint=1.8.4=py36_0
  - pyopenssl=17.5.0=py36_1
  - pyparsing=2.2.0=py36_0
  - pyqt=5.6.0=py36_5
  - pysocks=1.6.8=py36_1
  - requests=2.18.4=py36_1
  - resampy=0.2.0=py36_1
  - setuptools=39.0.1=py36_0
  - sip=4.18=py36_1
  - termcolor=1.1.0=py36_1
  - tornado=5.0.2=py36_0
  - urllib3=1.22=py36_0
  - webencodings=0.5=py36_0
  - wheel=0.31.0=py36_0
  - x264=20131217=3
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - cuda90=1.0=h6433d27_0
  - cuda91=1.0=h4c16780_0
  - pytorch=0.4.0=py36_cuda9.1.85_cudnn7.1.2_1
  - torchvision=0.2.1=py36_1
  - pip:
    - cython==0.28.2
    - imgaug==0.2.5
    - networkx==2.1
    - opencv-python==3.4.1.15
    - pywavelets==0.5.2
    - pyzmq==17.0.0
    - scikit-image==0.13.1
    - torch==0.4.0
    - torchfile==0.1.0
    - torchnet==0.0.2
    - visdom==0.1.7
prefix: /home/juliano/anaconda3/envs/pytorch

